In [7]:
from chemicalx.data import DrugPairBatch, BatchGenerator, DrugCombDB
import torch
import pandas as pd
import numpy as np
from src.model.multi_deep_dds import MultiDeepDDS


loader = DrugCombDB()

context_set = loader.get_context_features()
drug_set = loader.get_drug_features()
triplets = loader.get_labeled_triples()

train, test = triplets.train_test_split(0.8)

generator = BatchGenerator(batch_size=32,context_features=True, drug_features=True,drug_molecules=True,
                           context_feature_set=context_set, drug_feature_set=drug_set, labeled_triples=train)

model = MultiDeepDDS(context_channels=len(generator.context_feature_set))
for i in generator:
    sample =i
# model.load_state_dict(torch.load("saved_models/model.pt"))
model.eval()


MultiDeepDDS(
  (cell_mlp): MultiLayerPerceptron(
    (layers): ModuleList(
      (0): Linear(in_features=112, out_features=32, bias=True)
      (1-2): 2 x Linear(in_features=32, out_features=32, bias=True)
    )
  )
  (drug_conv2): GraphIsomorphismNetwork(
    (layers): ModuleList(
      (0): GraphIsomorphismConv(
        (mlp): MultiLayerPerceptron(
          (layers): ModuleList(
            (0-1): 2 x Linear(in_features=70, out_features=70, bias=True)
          )
        )
      )
      (1): GraphIsomorphismConv(
        (mlp): MultiLayerPerceptron(
          (layers): ModuleList(
            (0): Linear(in_features=70, out_features=140, bias=True)
            (1): Linear(in_features=140, out_features=140, bias=True)
          )
        )
      )
      (2): GraphIsomorphismConv(
        (mlp): MultiLayerPerceptron(
          (layers): ModuleList(
            (0): Linear(in_features=140, out_features=280, bias=True)
            (1): Linear(in_features=280, out_features=280, bias=Tru

In [4]:
model(sample.context_features, sample.drug_molecules_left, sample.drug_molecules_right,plot=True)

(24, 32)
(24, 32)
(24, 32)
(24, 32)


tensor([[0.5009],
        [0.2954],
        [0.2954],
        [0.2954],
        [0.3332],
        [0.2040],
        [0.2184],
        [0.2540],
        [0.2169],
        [0.2767],
        [0.3378],
        [0.3021],
        [0.2032],
        [0.2030],
        [0.2579],
        [0.2627],
        [0.1996],
        [0.2760],
        [0.2542],
        [0.1917],
        [0.2642],
        [0.7501],
        [0.5923],
        [0.2954]], grad_fn=<SigmoidBackward0>)

In [2]:
import matplotlib 
matplotlib.use("TkAgg")
import matplotlib.pyplot as plt

In [7]:
sample.drug_molecules_left[0].visualize()
plt.show()

In [3]:

pd.DataFrame([model._forward_molecules_gcn(sample.drug_molecules_left)[0].detach().numpy()]).T.plot()
plt.show()

In [4]:
pd.DataFrame([model._forward_molecules_gcn(sample.drug_molecules_left)[0].detach().numpy()]).T.plot()
plt.show()

In [8]:
model._forward_molecules_gcn(sample.drug_molecules_left)[0]

tensor([ 0.0660,  0.0220,  0.0213, -0.0059, -0.0547, -0.0398,  0.0395,  0.0318,
        -0.0855, -0.0203,  0.0005, -0.0449,  0.0147,  0.0048, -0.0619, -0.0187,
        -0.0726,  0.0600, -0.0562, -0.0751, -0.0398, -0.0276, -0.0358,  0.0641,
        -0.0469,  0.0126, -0.0191, -0.0875, -0.0548,  0.0232,  0.0802, -0.0485],
       grad_fn=<SelectBackward0>)

In [9]:
model._forward_molecules_gin(sample.drug_molecules_left)[0]

tensor([ 2.8079, -4.9001, -5.7083,  0.2397,  1.0207,  0.2084,  3.4843,  1.1955,
        -7.4326,  1.8987,  3.4927,  3.2551,  0.3835,  0.1511, -2.7930,  5.9844,
         0.3483,  5.3080, -0.2741, -1.0815, -1.8215, -0.5139,  2.0051, -3.7820,
        -3.8098, -2.1066,  3.6106, -1.0428,  1.2884, -4.0015,  1.1205, -4.3926],
       grad_fn=<SelectBackward0>)